### ISSUE TITLE
verbose output as a config option

### ISSUE THREAD

**Issue by vnev** [ark-lang/arkade#44]
I think its a good idea to have an option to enable/disable verbose output in the config file, under the `config` section. so we can have:

````toml
[config]
verbose = true
````

to enable verbose output, and similarly `verbose = false` for disable.
