### ISSUE TITLE
Change configuration to support SSH/Token auth

### ISSUE THREAD

**Issue by felixangell** [ark-lang/arkade#62]
I'm writing up the reference, and I was thinking about the authentication options, this is the current config file (or the minimum for one):

```toml
[config]
github_username = "felixangell"
token = "da39a3ee5e6b4b0d3255bfef95601890afd80709"
```

This is the new idea
```toml
[config]
#stuff

[config.github]
# token
auth = [ "token", ["felixangell", "da39a3ee5e6b4b0d3255bfef95601890afd80709"] ]

# ssh
auth = [ "ssh", ["felixangell", "/path/to/id_rsa", "/path/to/id_rsa.pub"] ]
```

This shouldn't be tricky to do, and isn't of the upmost importance until I port everything to libgit2.
